# coding: utf-8


# This file was *autogenerated* from the file common.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0)#!/usr/bin/env python

# In[1]:


def ord(p, x):
    if x == _sage_const_0 :
        return Infinity
    return ([n for (q, n) in x.factor() if q == p] + [_sage_const_0 ])[_sage_const_0 ]


# In[2]:


def ord_vector(p, m, column):
    return min(ord(p, x) for x in m[:,column].coefficients())

